// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: moduels/playerModule/playerProto/player.proto

package playerProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	RoleCode      int32                  `protobuf:"varint,4,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfile) Reset() {
	*x = PlayerProfile{}
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfile) ProtoMessage() {}

func (x *PlayerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfile.ProtoReflect.Descriptor instead.
func (*PlayerProfile) Descriptor() ([]byte, []int) {
	return file_moduels_playerModule_playerProto_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PlayerProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerProfile) GetRoleCode() int32 {
	if x != nil {
		return x.RoleCode
	}
	return 0
}

func (x *PlayerProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PlayerProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CredentialSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialSearchReq) Reset() {
	*x = CredentialSearchReq{}
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialSearchReq) ProtoMessage() {}

func (x *CredentialSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialSearchReq.ProtoReflect.Descriptor instead.
func (*CredentialSearchReq) Descriptor() ([]byte, []int) {
	return file_moduels_playerModule_playerProto_player_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialSearchReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CredentialSearchReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type FindOnePlayerProfileToRefreshReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOnePlayerProfileToRefreshReq) Reset() {
	*x = FindOnePlayerProfileToRefreshReq{}
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOnePlayerProfileToRefreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOnePlayerProfileToRefreshReq) ProtoMessage() {}

func (x *FindOnePlayerProfileToRefreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOnePlayerProfileToRefreshReq.ProtoReflect.Descriptor instead.
func (*FindOnePlayerProfileToRefreshReq) Descriptor() ([]byte, []int) {
	return file_moduels_playerModule_playerProto_player_proto_rawDescGZIP(), []int{2}
}

func (x *FindOnePlayerProfileToRefreshReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetPlayerSavingAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerSavingAccountReq) Reset() {
	*x = GetPlayerSavingAccountReq{}
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerSavingAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerSavingAccountReq) ProtoMessage() {}

func (x *GetPlayerSavingAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerSavingAccountReq.ProtoReflect.Descriptor instead.
func (*GetPlayerSavingAccountReq) Descriptor() ([]byte, []int) {
	return file_moduels_playerModule_playerProto_player_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerSavingAccountReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetPlayerSavingAccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerSavingAccountRes) Reset() {
	*x = GetPlayerSavingAccountRes{}
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerSavingAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerSavingAccountRes) ProtoMessage() {}

func (x *GetPlayerSavingAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_playerModule_playerProto_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerSavingAccountRes.ProtoReflect.Descriptor instead.
func (*GetPlayerSavingAccountRes) Descriptor() ([]byte, []int) {
	return file_moduels_playerModule_playerProto_player_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayerSavingAccountRes) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetPlayerSavingAccountRes) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

var File_moduels_playerModule_playerProto_player_proto protoreflect.FileDescriptor

const file_moduels_playerModule_playerProto_player_proto_rawDesc = "" +
	"\n" +
	"-moduels/playerModule/playerProto/player.proto\x12\vplayerProto\"\xab\x01\n" +
	"\rPlayerProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\broleCode\x18\x04 \x01(\x05R\broleCode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"G\n" +
	"\x13CredentialSearchReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	" FindOnePlayerProfileToRefreshReq\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\"7\n" +
	"\x19GetPlayerSavingAccountReq\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\"Q\n" +
	"\x19GetPlayerSavingAccountRes\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance2\xbb\x02\n" +
	"\x11PlayerGrpcService\x12P\n" +
	"\x10CredentialSearch\x12 .playerProto.CredentialSearchReq\x1a\x1a.playerProto.PlayerProfile\x12j\n" +
	"\x1dFindOnePlayerProfileToRefresh\x12-.playerProto.FindOnePlayerProfileToRefreshReq\x1a\x1a.playerProto.PlayerProfile\x12h\n" +
	"\x16GetPlayerSavingAccount\x12&.playerProto.GetPlayerSavingAccountReq\x1a&.playerProto.GetPlayerSavingAccountResB\x0fZ\r./playerProtob\x06proto3"

var (
	file_moduels_playerModule_playerProto_player_proto_rawDescOnce sync.Once
	file_moduels_playerModule_playerProto_player_proto_rawDescData []byte
)

func file_moduels_playerModule_playerProto_player_proto_rawDescGZIP() []byte {
	file_moduels_playerModule_playerProto_player_proto_rawDescOnce.Do(func() {
		file_moduels_playerModule_playerProto_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moduels_playerModule_playerProto_player_proto_rawDesc), len(file_moduels_playerModule_playerProto_player_proto_rawDesc)))
	})
	return file_moduels_playerModule_playerProto_player_proto_rawDescData
}

var file_moduels_playerModule_playerProto_player_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_moduels_playerModule_playerProto_player_proto_goTypes = []any{
	(*PlayerProfile)(nil),                    // 0: playerProto.PlayerProfile
	(*CredentialSearchReq)(nil),              // 1: playerProto.CredentialSearchReq
	(*FindOnePlayerProfileToRefreshReq)(nil), // 2: playerProto.FindOnePlayerProfileToRefreshReq
	(*GetPlayerSavingAccountReq)(nil),        // 3: playerProto.GetPlayerSavingAccountReq
	(*GetPlayerSavingAccountRes)(nil),        // 4: playerProto.GetPlayerSavingAccountRes
}
var file_moduels_playerModule_playerProto_player_proto_depIdxs = []int32{
	1, // 0: playerProto.PlayerGrpcService.CredentialSearch:input_type -> playerProto.CredentialSearchReq
	2, // 1: playerProto.PlayerGrpcService.FindOnePlayerProfileToRefresh:input_type -> playerProto.FindOnePlayerProfileToRefreshReq
	3, // 2: playerProto.PlayerGrpcService.GetPlayerSavingAccount:input_type -> playerProto.GetPlayerSavingAccountReq
	0, // 3: playerProto.PlayerGrpcService.CredentialSearch:output_type -> playerProto.PlayerProfile
	0, // 4: playerProto.PlayerGrpcService.FindOnePlayerProfileToRefresh:output_type -> playerProto.PlayerProfile
	4, // 5: playerProto.PlayerGrpcService.GetPlayerSavingAccount:output_type -> playerProto.GetPlayerSavingAccountRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moduels_playerModule_playerProto_player_proto_init() }
func file_moduels_playerModule_playerProto_player_proto_init() {
	if File_moduels_playerModule_playerProto_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moduels_playerModule_playerProto_player_proto_rawDesc), len(file_moduels_playerModule_playerProto_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moduels_playerModule_playerProto_player_proto_goTypes,
		DependencyIndexes: file_moduels_playerModule_playerProto_player_proto_depIdxs,
		MessageInfos:      file_moduels_playerModule_playerProto_player_proto_msgTypes,
	}.Build()
	File_moduels_playerModule_playerProto_player_proto = out.File
	file_moduels_playerModule_playerProto_player_proto_goTypes = nil
	file_moduels_playerModule_playerProto_player_proto_depIdxs = nil
}
