// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package paymentDI

import (
	"github.com/google/wire"
	"gitnub.com/hifat/hero-sekai-shop-microservice/config"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/paymentModule/paymentHandler"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/paymentModule/paymentRepository"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/paymentModule/paymentUsecase"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/playerModule/playerRepository"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/playerModule/playerUsecase"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitPayment(cfg *config.Config, db *mongo.Client) paymentHandler.Handler {
	iPaymentRepository := paymentRepository.NewPayment(db)
	iPaymentUsecase := paymentUsecase.NewPayment(cfg, iPaymentRepository)
	paymentGrpc := paymentHandler.NewPaymentGrpc(cfg, iPaymentUsecase)
	paymentHttp := paymentHandler.NewPaymentHttp(cfg, iPaymentUsecase)
	handler := paymentHandler.NewHandler(paymentGrpc, paymentHttp)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(paymentRepository.NewPayment, playerRepository.NewPlayer, playerRepository.NewPlayerTransaction)

var UsecaseSet = wire.NewSet(paymentUsecase.NewPayment, playerUsecase.NewPlayerTransaction)

var HandlerSet = wire.NewSet(paymentHandler.NewHandler, paymentHandler.NewPaymentHttp, paymentHandler.NewPaymentGrpc)
