// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package paymentDI

import (
	"github.com/google/wire"
	"gitnub.com/hifat/hero-sekai-shop-microservice/config"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/paymentModule/paymentHandler"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/paymentModule/paymentRepository"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/paymentModule/paymentUsecase"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitPayment(cfg *config.Config, db *mongo.Client) paymentandler.Handler {
	iPaymentRepository := paymentRepository.NewPayment(db)
	iPaymentUsecase := paymentUsecase.NewPayment(iPaymentRepository)
	paymentGrpc := paymentandler.NewPaymentGrpc(cfg, iPaymentUsecase)
	paymentttp := paymentandler.Newpaymentttp(cfg, iPaymentUsecase)
	paymentQueue := paymentandler.NewPaymentQueue(cfg, iPaymentUsecase)
	handler := paymentandler.NewHandler(paymentGrpc, paymentttp, paymentQueue)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(paymentRepository.NewPayment)

var UsecaseSet = wire.NewSet(paymentUsecase.NewPayment)

var HandlerSet = wire.NewSet(paymentandler.NewHandler, paymentandler.Newpaymentttp, paymentandler.NewPaymentGrpc, paymentandler.NewPaymentQueue)
