// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: moduels/inventory/inventoryProto/inventory.proto

package inventoryProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsAvailableToSellReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *IsAvailableToSellReq) Reset() {
	*x = IsAvailableToSellReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moduels_inventory_inventoryProto_inventory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsAvailableToSellReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAvailableToSellReq) ProtoMessage() {}

func (x *IsAvailableToSellReq) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_inventory_inventoryProto_inventory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAvailableToSellReq.ProtoReflect.Descriptor instead.
func (*IsAvailableToSellReq) Descriptor() ([]byte, []int) {
	return file_moduels_inventory_inventoryProto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *IsAvailableToSellReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type IsAvailableToSellRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAvailable bool `protobuf:"varint,1,opt,name=IsAvailable,proto3" json:"IsAvailable,omitempty"`
}

func (x *IsAvailableToSellRes) Reset() {
	*x = IsAvailableToSellRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moduels_inventory_inventoryProto_inventory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsAvailableToSellRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAvailableToSellRes) ProtoMessage() {}

func (x *IsAvailableToSellRes) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_inventory_inventoryProto_inventory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAvailableToSellRes.ProtoReflect.Descriptor instead.
func (*IsAvailableToSellRes) Descriptor() ([]byte, []int) {
	return file_moduels_inventory_inventoryProto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *IsAvailableToSellRes) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_moduels_inventory_inventoryProto_inventory_proto protoreflect.FileDescriptor

var file_moduels_inventory_inventoryProto_inventory_proto_rawDesc = []byte{
	0x0a, 0x30, 0x6d, 0x6f, 0x64, 0x75, 0x65, 0x6c, 0x73, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x32, 0x0a, 0x14, 0x49, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x54, 0x6f, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x14, 0x49, 0x73, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x6f, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x49, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x32, 0x77, 0x0a, 0x14, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x47, 0x72, 0x70,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x11, 0x49, 0x73, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x6f, 0x53, 0x65, 0x6c, 0x6c, 0x12, 0x24, 0x2e,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49,
	0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x6f, 0x53, 0x65, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x54, 0x6f, 0x53, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_moduels_inventory_inventoryProto_inventory_proto_rawDescOnce sync.Once
	file_moduels_inventory_inventoryProto_inventory_proto_rawDescData = file_moduels_inventory_inventoryProto_inventory_proto_rawDesc
)

func file_moduels_inventory_inventoryProto_inventory_proto_rawDescGZIP() []byte {
	file_moduels_inventory_inventoryProto_inventory_proto_rawDescOnce.Do(func() {
		file_moduels_inventory_inventoryProto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(file_moduels_inventory_inventoryProto_inventory_proto_rawDescData)
	})
	return file_moduels_inventory_inventoryProto_inventory_proto_rawDescData
}

var file_moduels_inventory_inventoryProto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moduels_inventory_inventoryProto_inventory_proto_goTypes = []interface{}{
	(*IsAvailableToSellReq)(nil), // 0: inventoryProto.IsAvailableToSellReq
	(*IsAvailableToSellRes)(nil), // 1: inventoryProto.IsAvailableToSellRes
}
var file_moduels_inventory_inventoryProto_inventory_proto_depIdxs = []int32{
	0, // 0: inventoryProto.InventoryGrpcService.IsAvailableToSell:input_type -> inventoryProto.IsAvailableToSellReq
	1, // 1: inventoryProto.InventoryGrpcService.IsAvailableToSell:output_type -> inventoryProto.IsAvailableToSellRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moduels_inventory_inventoryProto_inventory_proto_init() }
func file_moduels_inventory_inventoryProto_inventory_proto_init() {
	if File_moduels_inventory_inventoryProto_inventory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_moduels_inventory_inventoryProto_inventory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsAvailableToSellReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moduels_inventory_inventoryProto_inventory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsAvailableToSellRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_moduels_inventory_inventoryProto_inventory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moduels_inventory_inventoryProto_inventory_proto_goTypes,
		DependencyIndexes: file_moduels_inventory_inventoryProto_inventory_proto_depIdxs,
		MessageInfos:      file_moduels_inventory_inventoryProto_inventory_proto_msgTypes,
	}.Build()
	File_moduels_inventory_inventoryProto_inventory_proto = out.File
	file_moduels_inventory_inventoryProto_inventory_proto_rawDesc = nil
	file_moduels_inventory_inventoryProto_inventory_proto_goTypes = nil
	file_moduels_inventory_inventoryProto_inventory_proto_depIdxs = nil
}
