// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: moduels/inventoryModule/inventoryProto/inventory.proto

package inventoryProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsAvailableToSellReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAvailableToSellReq) Reset() {
	*x = IsAvailableToSellReq{}
	mi := &file_moduels_inventoryModule_inventoryProto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAvailableToSellReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAvailableToSellReq) ProtoMessage() {}

func (x *IsAvailableToSellReq) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_inventoryModule_inventoryProto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAvailableToSellReq.ProtoReflect.Descriptor instead.
func (*IsAvailableToSellReq) Descriptor() ([]byte, []int) {
	return file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *IsAvailableToSellReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type IsAvailableToSellRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=IsAvailable,proto3" json:"IsAvailable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAvailableToSellRes) Reset() {
	*x = IsAvailableToSellRes{}
	mi := &file_moduels_inventoryModule_inventoryProto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAvailableToSellRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAvailableToSellRes) ProtoMessage() {}

func (x *IsAvailableToSellRes) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_inventoryModule_inventoryProto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAvailableToSellRes.ProtoReflect.Descriptor instead.
func (*IsAvailableToSellRes) Descriptor() ([]byte, []int) {
	return file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *IsAvailableToSellRes) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_moduels_inventoryModule_inventoryProto_inventory_proto protoreflect.FileDescriptor

const file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDesc = "" +
	"\n" +
	"6moduels/inventoryModule/inventoryProto/inventory.proto\x12\x0einventoryProto\"2\n" +
	"\x14IsAvailableToSellReq\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\"8\n" +
	"\x14IsAvailableToSellRes\x12 \n" +
	"\vIsAvailable\x18\x01 \x01(\bR\vIsAvailable2w\n" +
	"\x14InventoryGrpcService\x12_\n" +
	"\x11IsAvailableToSell\x12$.inventoryProto.IsAvailableToSellReq\x1a$.inventoryProto.IsAvailableToSellResB\x12Z\x10./inventoryProtob\x06proto3"

var (
	file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDescOnce sync.Once
	file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDescData []byte
)

func file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDescGZIP() []byte {
	file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDescOnce.Do(func() {
		file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDesc), len(file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDesc)))
	})
	return file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDescData
}

var file_moduels_inventoryModule_inventoryProto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moduels_inventoryModule_inventoryProto_inventory_proto_goTypes = []any{
	(*IsAvailableToSellReq)(nil), // 0: inventoryProto.IsAvailableToSellReq
	(*IsAvailableToSellRes)(nil), // 1: inventoryProto.IsAvailableToSellRes
}
var file_moduels_inventoryModule_inventoryProto_inventory_proto_depIdxs = []int32{
	0, // 0: inventoryProto.InventoryGrpcService.IsAvailableToSell:input_type -> inventoryProto.IsAvailableToSellReq
	1, // 1: inventoryProto.InventoryGrpcService.IsAvailableToSell:output_type -> inventoryProto.IsAvailableToSellRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moduels_inventoryModule_inventoryProto_inventory_proto_init() }
func file_moduels_inventoryModule_inventoryProto_inventory_proto_init() {
	if File_moduels_inventoryModule_inventoryProto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDesc), len(file_moduels_inventoryModule_inventoryProto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moduels_inventoryModule_inventoryProto_inventory_proto_goTypes,
		DependencyIndexes: file_moduels_inventoryModule_inventoryProto_inventory_proto_depIdxs,
		MessageInfos:      file_moduels_inventoryModule_inventoryProto_inventory_proto_msgTypes,
	}.Build()
	File_moduels_inventoryModule_inventoryProto_inventory_proto = out.File
	file_moduels_inventoryModule_inventoryProto_inventory_proto_goTypes = nil
	file_moduels_inventoryModule_inventoryProto_inventory_proto_depIdxs = nil
}
