// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/google/wire"
	"gitnub.com/hifat/hero-sekai-shop-microservice/config"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/auth/authHandler"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/auth/authRepository"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/auth/authUsecase"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitAuth(cfg *config.Config, db *mongo.Client) authHandler.Handler {
	iAuthRepository := authRepository.NewAuth(db)
	iAuthUsecase := authUsecase.NewAuth(iAuthRepository)
	authHttp := authHandler.NewAuthHttp(cfg, iAuthUsecase)
	authGrpc := authHandler.NewAuthGrpc(iAuthUsecase)
	handler := authHandler.NewHandler(authHttp, authGrpc)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(authRepository.NewAuth)

var UsecaseSet = wire.NewSet(authUsecase.NewAuth)

var HandlerSet = wire.NewSet(authHandler.NewHandler, authHandler.NewAuthHttp, authHandler.NewAuthGrpc)
