// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: moduels/authModule/authProto/auth.proto

package authProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessTokenSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenSearchReq) Reset() {
	*x = AccessTokenSearchReq{}
	mi := &file_moduels_authModule_authProto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenSearchReq) ProtoMessage() {}

func (x *AccessTokenSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_authModule_authProto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenSearchReq.ProtoReflect.Descriptor instead.
func (*AccessTokenSearchReq) Descriptor() ([]byte, []int) {
	return file_moduels_authModule_authProto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AccessTokenSearchReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AccessTokenSearchRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenSearchRes) Reset() {
	*x = AccessTokenSearchRes{}
	mi := &file_moduels_authModule_authProto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenSearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenSearchRes) ProtoMessage() {}

func (x *AccessTokenSearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_authModule_authProto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenSearchRes.ProtoReflect.Descriptor instead.
func (*AccessTokenSearchRes) Descriptor() ([]byte, []int) {
	return file_moduels_authModule_authProto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTokenSearchRes) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type RolesCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolesCountReq) Reset() {
	*x = RolesCountReq{}
	mi := &file_moduels_authModule_authProto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesCountReq) ProtoMessage() {}

func (x *RolesCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_authModule_authProto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesCountReq.ProtoReflect.Descriptor instead.
func (*RolesCountReq) Descriptor() ([]byte, []int) {
	return file_moduels_authModule_authProto_auth_proto_rawDescGZIP(), []int{2}
}

type RolesCountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolesCountRes) Reset() {
	*x = RolesCountRes{}
	mi := &file_moduels_authModule_authProto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesCountRes) ProtoMessage() {}

func (x *RolesCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_moduels_authModule_authProto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesCountRes.ProtoReflect.Descriptor instead.
func (*RolesCountRes) Descriptor() ([]byte, []int) {
	return file_moduels_authModule_authProto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RolesCountRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_moduels_authModule_authProto_auth_proto protoreflect.FileDescriptor

const file_moduels_authModule_authProto_auth_proto_rawDesc = "" +
	"\n" +
	"'moduels/authModule/authProto/auth.proto\x12\tauthProto\"8\n" +
	"\x14AccessTokenSearchReq\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"0\n" +
	"\x14AccessTokenSearchRes\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid\"\x0f\n" +
	"\rRolesCountReq\"%\n" +
	"\rRolesCountRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\xaa\x01\n" +
	"\x0fAuthGrpcService\x12U\n" +
	"\x11AccessTokenSearch\x12\x1f.authProto.AccessTokenSearchReq\x1a\x1f.authProto.AccessTokenSearchRes\x12@\n" +
	"\n" +
	"RolesCount\x12\x18.authProto.RolesCountReq\x1a\x18.authProto.RolesCountResB\rZ\v./authProtob\x06proto3"

var (
	file_moduels_authModule_authProto_auth_proto_rawDescOnce sync.Once
	file_moduels_authModule_authProto_auth_proto_rawDescData []byte
)

func file_moduels_authModule_authProto_auth_proto_rawDescGZIP() []byte {
	file_moduels_authModule_authProto_auth_proto_rawDescOnce.Do(func() {
		file_moduels_authModule_authProto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moduels_authModule_authProto_auth_proto_rawDesc), len(file_moduels_authModule_authProto_auth_proto_rawDesc)))
	})
	return file_moduels_authModule_authProto_auth_proto_rawDescData
}

var file_moduels_authModule_authProto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_moduels_authModule_authProto_auth_proto_goTypes = []any{
	(*AccessTokenSearchReq)(nil), // 0: authProto.AccessTokenSearchReq
	(*AccessTokenSearchRes)(nil), // 1: authProto.AccessTokenSearchRes
	(*RolesCountReq)(nil),        // 2: authProto.RolesCountReq
	(*RolesCountRes)(nil),        // 3: authProto.RolesCountRes
}
var file_moduels_authModule_authProto_auth_proto_depIdxs = []int32{
	0, // 0: authProto.AuthGrpcService.AccessTokenSearch:input_type -> authProto.AccessTokenSearchReq
	2, // 1: authProto.AuthGrpcService.RolesCount:input_type -> authProto.RolesCountReq
	1, // 2: authProto.AuthGrpcService.AccessTokenSearch:output_type -> authProto.AccessTokenSearchRes
	3, // 3: authProto.AuthGrpcService.RolesCount:output_type -> authProto.RolesCountRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moduels_authModule_authProto_auth_proto_init() }
func file_moduels_authModule_authProto_auth_proto_init() {
	if File_moduels_authModule_authProto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moduels_authModule_authProto_auth_proto_rawDesc), len(file_moduels_authModule_authProto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moduels_authModule_authProto_auth_proto_goTypes,
		DependencyIndexes: file_moduels_authModule_authProto_auth_proto_depIdxs,
		MessageInfos:      file_moduels_authModule_authProto_auth_proto_msgTypes,
	}.Build()
	File_moduels_authModule_authProto_auth_proto = out.File
	file_moduels_authModule_authProto_auth_proto_goTypes = nil
	file_moduels_authModule_authProto_auth_proto_depIdxs = nil
}
