// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package player

import (
	"github.com/google/wire"
	"gitnub.com/hifat/hero-sekai-shop-microservice/config"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/player/playerHandler"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/player/playerRepository"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/player/playerUsecase"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitPlayer(cfg *config.Config, db *mongo.Client) playerHandler.Handler {
	iPlayerRepository := playerRepository.NewPlayer(db)
	iPlayerUsecase := playerUsecase.NewPlayer(iPlayerRepository)
	playerHttp := playerHandler.NewPlayerHttp(iPlayerUsecase)
	playerGrpc := playerHandler.NewPlayerGrpc(iPlayerUsecase)
	playerQueue := playerHandler.NewPlayerQueue(iPlayerUsecase)
	handler := playerHandler.NewHandler(playerHttp, playerGrpc, playerQueue)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(playerRepository.NewPlayer)

var UsecaseSet = wire.NewSet(playerUsecase.NewPlayer)

var HandlerSet = wire.NewSet(playerHandler.NewHandler, playerHandler.NewPlayerHttp, playerHandler.NewPlayerGrpc, playerHandler.NewPlayerQueue)
