// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inventory

import (
	"github.com/google/wire"
	"gitnub.com/hifat/hero-sekai-shop-microservice/config"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/inventory/inventoryHandler"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/inventory/inventoryRepository"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/inventory/inventoryUsecase"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitInventory(cfg *config.Config, db *mongo.Client) inventoryHandler.Handler {
	iInventoryRepository := inventoryRepository.NewInventory(db)
	iInventoryUsecase := inventoryUsecase.NewInventory(iInventoryRepository)
	inventoryHttp := inventoryHandler.NewInventoryHttp(cfg, iInventoryUsecase)
	inventoryGrpc := inventoryHandler.NewInventoryGrpc(iInventoryUsecase)
	inventoryQueue := inventoryHandler.NewInventoryQueue(cfg, iInventoryUsecase)
	handler := inventoryHandler.NewHandler(inventoryHttp, inventoryGrpc, inventoryQueue)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(inventoryRepository.NewInventory)

var UsecaseSet = wire.NewSet(inventoryUsecase.NewInventory)

var HandlerSet = wire.NewSet(inventoryHandler.NewHandler, inventoryHandler.NewInventoryHttp, inventoryHandler.NewInventoryGrpc, inventoryHandler.NewInventoryQueue)
