// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middleware

import (
	"github.com/google/wire"
	"gitnub.com/hifat/hero-sekai-shop-microservice/config"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/middleware/middlewareHandler"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/middleware/middlewareRepository"
	"gitnub.com/hifat/hero-sekai-shop-microservice/moduels/middleware/middlewareUsecase"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitMiddleware(cfg *config.Config, db *mongo.Client) middlewareHandler.Handler {
	iMiddlewareRepository := middlewareRepository.NewMiddleware(db)
	iMiddlewareUsecase := middlewareUsecase.NewMiddleware(iMiddlewareRepository)
	middlewareHttp := middlewareHandler.NewHttp(iMiddlewareUsecase)
	handler := middlewareHandler.NewHandler(middlewareHttp)
	return handler
}

// wire.go:

var RepoSet = wire.NewSet(middlewareRepository.NewMiddleware)

var UsecaseSet = wire.NewSet(middlewareUsecase.NewMiddleware)

var HandlerSet = wire.NewSet(middlewareHandler.NewHandler, middlewareHandler.NewHttp)
